import express from 'express';
import { commitCapture } from './server/capture.js';
import { finalizeEvidence, startEvidence, uploadEvidence } from './server/evidence.js';
import { analyzeEvidenceText } from './server/evidence-analysis.js';
import { getVaultEvidenceDetail, listVaultEvidence, previewVaultEvidence } from './server/vault.js';
import { createAccount, updateAccountBalance } from './server/accounts.js';
import { createCreditCard } from './server/cards.js';
import { commitCreditCardInvoice, payCreditCardInvoice, previewCreditCardInvoice, reviewCreditCardInvoice } from './server/invoices.js';
import { analyzeCreditCardInvoiceImage } from './server/invoice-vision.js';
import { analyzeEvidenceWithAi } from './server/evidence-ai.js';
import { bootstrapSession } from './server/session.js';
import { getHomeData } from './server/home.js';
import { answerFinanceAssistant } from './server/assistant.js';
import { commitFinancialScreen } from './server/financial-screen.js';
import { findCommitmentPaymentMatches, findCommitmentPaymentMatchesBatch, payCommitment, undoCommitmentPayment } from './server/commitment-payments.js';
import { completeOpenFinanceConnection, disconnectOpenFinanceConnection, listOpenFinanceConnections, startOpenFinanceConnection, syncOpenFinanceConnection } from './server/open-finance.js';
import { selectHousehold } from './server/session.js';
import { acceptHouseholdInvite, createHouseholdInvite, getHouseholdSettings, removeHouseholdMember, renameHousehold, revokeHouseholdInvite, updateHouseholdMemberRole } from './server/household.js';
import { deleteHousehold, deletePersonalData, exportPrivacyData, getPrivacyStatus, recordPrivacyConsent } from './server/data-rights.js';

const app = express();
app.disable('x-powered-by');
const healthz = (_req: express.Request, res: express.Response) => res.json({ ok: true, service: 'nestbalance-api' });
app.get('/healthz', healthz);
app.get('/api/healthz', healthz);
app.post('/api/evidence/upload', express.raw({ type: '*/*', limit: '20mb' }), uploadEvidence);
app.use(express.json({ limit: '128kb' }));
app.post('/api/session/bootstrap', bootstrapSession);
app.post('/api/session/select-household', selectHousehold);
app.post('/api/household/settings', getHouseholdSettings);
app.post('/api/household/rename', renameHousehold);
app.post('/api/household/invite', createHouseholdInvite);
app.post('/api/household/invite/accept', acceptHouseholdInvite);
app.post('/api/household/invite/revoke', revokeHouseholdInvite);
app.post('/api/household/member/role', updateHouseholdMemberRole);
app.post('/api/household/member/remove', removeHouseholdMember);
app.post('/api/privacy/status', getPrivacyStatus);
app.post('/api/privacy/consent', recordPrivacyConsent);
app.post('/api/privacy/export', exportPrivacyData);
app.post('/api/privacy/delete-personal', deletePersonalData);
app.post('/api/privacy/delete-household', deleteHousehold);
app.post('/api/home', getHomeData);
app.post('/api/assistant/answer', answerFinanceAssistant);
app.post('/api/financial-screen/commit', commitFinancialScreen);
app.post('/api/commitments/match-payment', findCommitmentPaymentMatches);
app.post('/api/commitments/match-payments', findCommitmentPaymentMatchesBatch);
app.post('/api/commitments/pay', payCommitment);
app.post('/api/commitments/undo-payment', undoCommitmentPayment);
app.post('/api/open-finance/list', listOpenFinanceConnections);
app.post('/api/open-finance/start', startOpenFinanceConnection);
app.post('/api/open-finance/complete', completeOpenFinanceConnection);
app.post('/api/open-finance/sync', syncOpenFinanceConnection);
app.post('/api/open-finance/disconnect', disconnectOpenFinanceConnection);
app.post('/api/evidence/start', startEvidence);
app.post('/api/evidence/finalize', finalizeEvidence);
app.post('/api/evidence/analyze-text', analyzeEvidenceText);
app.post('/api/evidence/analyze-ai', analyzeEvidenceWithAi);
app.post('/api/vault/list', listVaultEvidence);
app.post('/api/vault/detail', getVaultEvidenceDetail);
app.post('/api/vault/preview', previewVaultEvidence);
app.post('/api/capture/commit', commitCapture);
app.post('/api/accounts/create', createAccount);
app.post('/api/accounts/update-balance', updateAccountBalance);
app.post('/api/cards/create', createCreditCard);
app.post('/api/invoices/preview', previewCreditCardInvoice);
app.post('/api/invoices/review', reviewCreditCardInvoice);
app.post('/api/invoices/analyze-image', analyzeCreditCardInvoiceImage);
app.post('/api/invoices/commit', commitCreditCardInvoice);
app.post('/api/invoices/pay', payCreditCardInvoice);
app.use((_req, res) => res.status(404).json({ ok: false, error: 'NOT_FOUND' }));

const port = Number(process.env.PORT || 8080);
app.listen(port, '0.0.0.0', () => console.log(`nestbalance-api listening on ${port}`));
