import type { Locale } from '../i18n/messages.js';

export function assistantSuggestions(locale:Locale){
  if(locale==='en') return {
    spend:'Can I spend R$ 500?',
    remaining:'How much is left to pay?',
    available:'How much do I have available?',
    ending:'Which installments end soon?',
    future:'What is already committed in the next months?',
    change:'Why did I spend more this month?',
    anomalies:'What looks unusual?'
  };
  if(locale==='es') return {
    spend:'¿Puedo gastar R$ 500?',
    remaining:'¿Cuánto falta pagar?',
    available:'¿Cuánto tengo disponible?',
    ending:'¿Qué cuotas terminan pronto?',
    future:'¿Qué ya está comprometido en los próximos meses?',
    change:'¿Por qué gasté más este mes?',
    anomalies:'¿Qué se ve fuera de lo normal?'
  };
  return {
    spend:'Dá para gastar R$ 500?',
    remaining:'Quanto ainda falta pagar?',
    available:'Quanto tenho disponível?',
    ending:'Quais parcelas terminam logo?',
    future:'O que já está comprometido nos próximos meses?',
    change:'Por que gastei mais este mês?',
    anomalies:'O que está estranho?'
  };
}

export function assistantCopy(locale:Locale){
  const s=assistantSuggestions(locale);
  if(locale==='en') return {
    s,
    accountBalance:'Known current balance',
    openCommitment:'Known open commitment',
    invoice:(key:string)=>`Card bill ${key}`,
    invoicePartial:'Card bill still under review',
    invoiceConfirmed:'Confirmed open card bill',
    simulationNeedTitle:'What amount do you want to simulate?',
    simulationNeedSummary:`Include the amount in your question, for example: “${s.spend}”.`,
    simulationTitle:(amount:string)=>`Simulation for ${amount}`,
    simulationSummary:(after:string,partial:number)=>`With the balances and known obligations right now, after this expense the projection would be ${after}.${partial?` ${partial} card bill${partial===1?' is':'s are'} still under review, so this may change.`:''} This is a simulation, not a spending recommendation.`,
    availableNow:'Available now',knownAccounts:(n:number)=>`${n} known account${n===1?'':'s'}`,
    knownObligations:'Known obligations',openItems:(n:number)=>`${n} open item${n===1?'':'s'}`,
    simulatedSpend:'Simulated expense',providedByYou:'Amount provided by you',
    projectedLeft:'Projected amount left',afterKnown:'After known obligations and the simulated expense',belowZero:'Would be below zero with the known data',
    noInstallmentsTitle:'No active installments are known.',
    noInstallmentsSummary:'I did not find reconciled installment plans yet.',
    endingTitle:'These installments end first.',closestTitle:'These are the installments closest to ending.',
    endingSummary:(n:number,released:string)=>`${n} plan${n===1?' ends':'s end'} within 3 installments. When they end, ${released} per month will no longer be committed, using the current amounts.`,
    noneEndingSoon:'No plan ends within the next 3 installments, but these are the closest ones.',
    installmentPurchase:'Installment purchase',
    installmentsLeft:(n:number,total?:number)=>`${n} installment${n===1?'':'s'} left${total?` out of ${total}`:''}`,
    noCompareTitle:'A previous month is still needed for comparison.',
    noCompareSummary:'I can explain the difference once there are expenses in both the current month and the previous month. I will not invent a comparison without data.',
    thisMonth:'This month',previousMonth:'Previous month',knownSpending:(n:number)=>`${n} known expense${n===1?'':'s'}`,
    topReason:(names:string[])=>names.length?` The largest increases came from ${names.join(', ')}.`:'',
    observedThisMonth:'Expense observed this month',
    spentMore:(amount:string)=>`You spent ${amount} more than the previous month.`,
    spentLess:(amount:string)=>`You spent ${amount} less than the previous month.`,
    sameLevel:'Your known spending is at the same level as the previous month.',
    spendingSummary:(now:string,previous:string,reason:string)=>`This month has ${now} in known expenses; the previous month had ${previous}.${reason} The comparison excludes transfers between your accounts and card-bill payments so the same expense is not counted twice.`,
    categoryIncrease:(before:string,after:string)=>`Category increase: ${before} → ${after}`,
    noAnomaliesTitle:'Nothing outside the known pattern stood out.',
    noAnomaliesSummary:'I did not find likely duplicates or values clearly above the available history this month. That does not guarantee everything is correct; it only means there was no strong signal in the known data.',
    anomalyTitle:(n:number)=>`I found ${n} item${n===1?'':'s'} worth checking.`,
    anomalySummary:'These are signals, not accusations of error. I only flag possible duplicates and values clearly above the history for the same description.',
    possibleDuplicate:'Possible duplicate',differentNormal:'Different from usual',
    duplicateSignalDetail:'The same description and amount appeared more than once on the same day. It may be correct, but it is worth checking.',
    spikeSignalDetail:'This amount is well above the recent history for the same description.',
    typicalHistory:(base:string,diff:string)=>`Typical history: ${base} · difference of ${diff}`,
    pendingCommitment:'Pending commitment',
    invoicePartialDetail:'Confirmed amount so far; the card bill is still under review',
    invoiceOpenDetail:'Confirmed card bill not paid yet',
    remainingTitle:'There are still known amounts to pay.',nothingPending:'Nothing known is pending right now.',
    remainingSummary:(count:number,partial:number)=>`NestBalance found ${count} open obligation${count===1?'':'s'} in this view.${partial?` ${partial} card bill${partial===1?' is':'s are'} still under review, so the total may increase.`:''}`,
    nothingPendingSummary:'There are no confirmed open commitments or card bills in the current data.',
    commitments:'Commitments',pendingItems:(n:number)=>`${n} pending item${n===1?'':'s'}`,
    openBills:'Open card bills',knownBills:(n:number)=>`${n} card bill${n===1?'':'s'} with a known amount`,
    accountCurrent:'Current balance reported for this account',
    availableTitle:'Known available balance',
    availableSummary:(n:number)=>`Adding ${n} active account${n===1?'':'s'} in this view.`,
    noAvailable:'There is no account with an available balance to add yet.',
    futureTitle:'Known commitments for the next months',
    futureSummary:'The forecast uses only confirmed recurring bills and installment plans that have already been reconciled.',
    monthlyBill:'Confirmed monthly recurring bill',
    installmentObserved:(current:number,total:number)=>`Installment ${current} of ${total} observed`,
    knownCommitments:(n:number)=>`${n} known commitment${n===1?'':'s'}`,
    unsupportedTitle:'I can answer using the data in this view.',
    unsupportedSummary:'Ask about available balance, what is left to pay, next months, a spending simulation, installments ending soon, why spending changed, or what looks unusual.'
  } as const;

  if(locale==='es') return {
    s,
    accountBalance:'Saldo actual conocido',
    openCommitment:'Compromiso abierto conocido',
    invoice:(key:string)=>`Tarjeta ${key}`,
    invoicePartial:'Tarjeta todavía en revisión',
    invoiceConfirmed:'Tarjeta abierta confirmada',
    simulationNeedTitle:'¿Qué valor quieres simular?',
    simulationNeedSummary:`Escribe el valor en la propia pregunta, por ejemplo: “${s.spend}”.`,
    simulationTitle:(amount:string)=>`Simulación de ${amount}`,
    simulationSummary:(after:string,partial:number)=>`Con los saldos y compromisos conocidos ahora, después de este gasto la previsión quedaría en ${after}.${partial?` Hay ${partial} tarjeta${partial===1?'':'s'} todavía en revisión, por lo que este valor puede cambiar.`:''} Es una simulación, no una recomendación de gasto.`,
    availableNow:'Disponible ahora',knownAccounts:(n:number)=>`${n} cuenta${n===1?'':'s'} conocida${n===1?'':'s'}`,
    knownObligations:'Compromisos conocidos',openItems:(n:number)=>`${n} elemento${n===1?'':'s'} abierto${n===1?'':'s'}`,
    simulatedSpend:'Gasto simulado',providedByYou:'Valor informado por ti',
    projectedLeft:'Quedaría en la previsión',afterKnown:'Después de compromisos conocidos y el gasto simulado',belowZero:'Quedaría por debajo de cero con los datos conocidos',
    noInstallmentsTitle:'No hay cuotas activas conocidas.',
    noInstallmentsSummary:'Todavía no encontré planes de cuotas conciliados.',
    endingTitle:'Estas cuotas terminan primero.',closestTitle:'Estas son las cuotas más cercanas al final.',
    endingSummary:(n:number,released:string)=>`${n} plan${n===1?' termina':'es terminan'} en hasta 3 cuotas. Cuando terminen, ${released} al mes dejarán de estar comprometidos, usando los valores actuales.`,
    noneEndingSoon:'Ningún plan termina en las próximas 3 cuotas, pero estos son los más cercanos al final.',
    installmentPurchase:'Compra en cuotas',
    installmentsLeft:(n:number,total?:number)=>`${n} cuota${n===1?'':'s'} pendiente${n===1?'':'s'}${total?` de ${total}`:''}`,
    noCompareTitle:'Todavía falta un mes anterior para comparar.',
    noCompareSummary:'Puedo explicar la diferencia cuando haya gastos registrados en el mes actual y en el anterior. No voy a inventar una comparación sin datos.',
    thisMonth:'Este mes',previousMonth:'Mes anterior',knownSpending:(n:number)=>`${n} gasto${n===1?'':'s'} conocido${n===1?'':'s'}`,
    topReason:(names:string[])=>names.length?` Los mayores aumentos vinieron de ${names.join(', ')}.`:'',
    observedThisMonth:'Gasto observado este mes',
    spentMore:(amount:string)=>`Gastaste ${amount} más que el mes anterior.`,
    spentLess:(amount:string)=>`Gastaste ${amount} menos que el mes anterior.`,
    sameLevel:'Tus gastos conocidos están al mismo nivel que el mes anterior.',
    spendingSummary:(now:string,previous:string,reason:string)=>`Este mes tiene ${now} en gastos conocidos; el mes anterior tuvo ${previous}.${reason} La comparación excluye transferencias entre tus cuentas y pagos de tarjeta para no contar el mismo gasto dos veces.`,
    categoryIncrease:(before:string,after:string)=>`Aumento en la categoría: ${before} → ${after}`,
    noAnomaliesTitle:'Nada fuera del patrón conocido llamó la atención.',
    noAnomaliesSummary:'No encontré duplicados probables ni valores claramente por encima del historial disponible este mes. Eso no garantiza que todo esté correcto; solo significa que no apareció una señal fuerte en los datos conocidos.',
    anomalyTitle:(n:number)=>`Encontré ${n} elemento${n===1?'':'s'} que conviene revisar.`,
    anomalySummary:'Son señales, no acusaciones de error. Solo marco posibles duplicados y valores claramente por encima del historial de la misma descripción.',
    possibleDuplicate:'Posible duplicado',differentNormal:'Valor diferente de lo normal',
    duplicateSignalDetail:'La misma descripción y el mismo valor aparecieron más de una vez el mismo día. Puede ser correcto, pero conviene revisarlo.',
    spikeSignalDetail:'Este valor está bastante por encima del historial reciente de la misma descripción.',
    typicalHistory:(base:string,diff:string)=>`Historial típico: ${base} · diferencia de ${diff}`,
    pendingCommitment:'Compromiso pendiente',
    invoicePartialDetail:'Valor confirmado hasta ahora; la tarjeta todavía está en revisión',
    invoiceOpenDetail:'Tarjeta confirmada y todavía no pagada',
    remainingTitle:'Todavía hay valores conocidos por pagar.',nothingPending:'No hay nada pendiente conocido ahora.',
    remainingSummary:(count:number,partial:number)=>`NestBalance encontró ${count} obligación${count===1?'':'es'} abierta${count===1?'':'s'} en esta visión.${partial?` Hay ${partial} tarjeta${partial===1?'':'s'} en revisión, por lo que el total puede aumentar.`:''}`,
    nothingPendingSummary:'No hay compromisos ni tarjetas abiertas confirmadas en los datos actuales.',
    commitments:'Compromisos',pendingItems:(n:number)=>`${n} elemento${n===1?'':'s'} pendiente${n===1?'':'s'}`,
    openBills:'Tarjetas abiertas',knownBills:(n:number)=>`${n} tarjeta${n===1?'':'s'} con valor conocido`,
    accountCurrent:'Saldo actual informado en esta cuenta',
    availableTitle:'Saldo disponible conocido',
    availableSummary:(n:number)=>`Sumando ${n} cuenta${n===1?'':'s'} activa${n===1?'':'s'} en esta visión.`,
    noAvailable:'Todavía no hay una cuenta con saldo disponible para sumar.',
    futureTitle:'Compromisos conocidos de los próximos meses',
    futureSummary:'La previsión usa solo cuentas recurrentes confirmadas y planes de cuotas ya conciliados.',
    monthlyBill:'Cuenta recurrente mensual',
    installmentObserved:(current:number,total:number)=>`Cuota ${current} de ${total} observada`,
    knownCommitments:(n:number)=>`${n} compromiso${n===1?'':'s'} conocido${n===1?'':'s'}`,
    unsupportedTitle:'Puedo responder con los datos de esta visión.',
    unsupportedSummary:'Pregunta por saldo disponible, cuánto falta pagar, próximos meses, simulación de gasto, cuotas que terminan, por qué cambiaron los gastos o qué parece fuera de lo normal.'
  } as const;

  return {
    s,
    accountBalance:'Saldo atual conhecido',
    openCommitment:'Compromisso aberto conhecido',
    invoice:(key:string)=>`Fatura ${key}`,
    invoicePartial:'Fatura ainda em revisão',
    invoiceConfirmed:'Fatura aberta confirmada',
    simulationNeedTitle:'Qual valor você quer simular?',
    simulationNeedSummary:`Escreva o valor na própria pergunta, por exemplo: “${s.spend}”.`,
    simulationTitle:(amount:string)=>`Simulação de ${amount}`,
    simulationSummary:(after:string,partial:number)=>`Com os saldos e obrigações conhecidos agora, depois desse gasto a projeção ficaria em ${after}.${partial?` Há ${partial} fatura${partial===1?'':'s'} ainda em revisão, então esse valor pode mudar.`:''} Isso é uma simulação, não uma recomendação de gasto.`,
    availableNow:'Disponível agora',knownAccounts:(n:number)=>`${n} conta${n===1?'':'s'} conhecida${n===1?'':'s'}`,
    knownObligations:'Obrigações conhecidas',openItems:(n:number)=>`${n} item${n===1?'':'s'} aberto${n===1?'':'s'}`,
    simulatedSpend:'Gasto simulado',providedByYou:'Valor informado por você',
    projectedLeft:'Restaria na projeção',afterKnown:'Após obrigações conhecidas e o gasto simulado',belowZero:'Ficaria abaixo de zero com os dados conhecidos',
    noInstallmentsTitle:'Nenhuma parcela ativa conhecida.',
    noInstallmentsSummary:'Não encontrei planos de parcelamento reconciliados ainda.',
    endingTitle:'Estas parcelas terminam primeiro.',closestTitle:'Estas são as parcelas mais próximas do fim.',
    endingSummary:(n:number,released:string)=>`${n} plano${n===1?' termina':'s terminam'} em até 3 parcelas. Quando acabarem, ${released} por mês deixam de estar comprometidos, considerando os valores atuais.`,
    noneEndingSoon:'Nenhum plano termina nas próximas 3 parcelas, mas estes são os mais próximos do fim.',
    installmentPurchase:'Compra parcelada',
    installmentsLeft:(n:number,total?:number)=>`${n===1?'Falta':'Faltam'} ${n} parcela${n===1?'':'s'}${total?` de ${total}`:''}`,
    noCompareTitle:'Ainda falta um mês anterior para comparar.',
    noCompareSummary:'Eu consigo explicar a diferença quando houver gastos registrados no mês atual e no mês anterior. Não vou inventar uma comparação sem base.',
    thisMonth:'Este mês',previousMonth:'Mês anterior',knownSpending:(n:number)=>`${n} gasto${n===1?'':'s'} conhecido${n===1?'':'s'}`,
    topReason:(names:string[])=>names.length?` As maiores altas vieram de ${names.join(', ')}.`:'',
    observedThisMonth:'Gasto observado neste mês',
    spentMore:(amount:string)=>`Você gastou ${amount} a mais que no mês anterior.`,
    spentLess:(amount:string)=>`Você gastou ${amount} a menos que no mês anterior.`,
    sameLevel:'Seus gastos conhecidos estão no mesmo nível do mês anterior.',
    spendingSummary:(now:string,previous:string,reason:string)=>`Este mês tem ${now} em gastos conhecidos; o mês anterior teve ${previous}.${reason} A comparação ignora transferências entre suas contas e pagamento de fatura para não contar a mesma despesa duas vezes.`,
    categoryIncrease:(before:string,after:string)=>`Alta na categoria: ${before} → ${after}`,
    noAnomaliesTitle:'Nada fora do padrão conhecido chamou atenção.',
    noAnomaliesSummary:'Não encontrei duplicidades prováveis nem valores claramente acima do histórico disponível neste mês. Isso não garante que esteja tudo certo; significa apenas que não apareceu um sinal forte nos dados conhecidos.',
    anomalyTitle:(n:number)=>`Encontrei ${n} ${n===1?'item':'itens'} que vale conferir.`,
    anomalySummary:'São sinais, não acusações de erro. Eu marco apenas possíveis duplicidades e valores bem acima do histórico da mesma descrição.',
    possibleDuplicate:'Possível duplicidade',differentNormal:'Valor diferente do normal',
    duplicateSignalDetail:'A mesma descrição e o mesmo valor apareceram mais de uma vez no mesmo dia. Pode estar certo, mas vale conferir.',
    spikeSignalDetail:'Este valor ficou bem acima do histórico recente com a mesma descrição.',
    typicalHistory:(base:string,diff:string)=>`Histórico típico: ${base} · diferença de ${diff}`,
    pendingCommitment:'Compromisso pendente',
    invoicePartialDetail:'Valor confirmado até agora; a fatura ainda está em revisão',
    invoiceOpenDetail:'Fatura confirmada e ainda não paga',
    remainingTitle:'Ainda há valores conhecidos para pagar.',nothingPending:'Nada pendente conhecido agora.',
    remainingSummary:(count:number,partial:number)=>`O NestBalance encontrou ${count} obrigação${count===1?'':'ões'} aberta${count===1?'':'s'} nesta visão.${partial?` ${partial} fatura${partial===1?' está':'s estão'} em revisão, então o total pode aumentar.`:''}`,
    nothingPendingSummary:'Não há compromissos nem faturas abertas confirmadas nos dados atuais.',
    commitments:'Compromissos',pendingItems:(n:number)=>`${n} item${n===1?'':'s'} pendente${n===1?'':'s'}`,
    openBills:'Faturas abertas',knownBills:(n:number)=>`${n} fatura${n===1?'':'s'} com valor conhecido`,
    accountCurrent:'Saldo atual informado nesta conta',
    availableTitle:'Saldo disponível conhecido',
    availableSummary:(n:number)=>`Somando ${n} conta${n===1?'':'s'} ativa${n===1?'':'s'} nesta visão.`,
    noAvailable:'Ainda não há uma conta com saldo disponível para somar.',
    futureTitle:'Compromissos conhecidos dos próximos meses',
    futureSummary:'A projeção usa apenas contas recorrentes confirmadas e planos de parcelas já reconciliados.',
    monthlyBill:'Conta recorrente mensal',
    installmentObserved:(current:number,total:number)=>`Parcela ${current} de ${total} observada`,
    knownCommitments:(n:number)=>`${n} compromisso${n===1?'':'s'} conhecido${n===1?'':'s'}`,
    unsupportedTitle:'Posso responder com os dados desta visão.',
    unsupportedSummary:'Pergunte sobre saldo disponível, quanto falta pagar, próximos meses, simulação de gasto, parcelas que terminam, por que os gastos mudaram ou o que parece fora do padrão.'
  } as const;
}
